%%                  solve_shapefit.m  by Tom Goldstein
%   Solve the shapefit minimization problem to recover the locations of n
%   points in d-dimensional space.
%   Inputs:
%     E:   a matrix that extracts edge vectors from a list of vertices by
%       computing pairwise differences.  If we are dealing with a cloud of
%       n points, and we have direction measurements on e edges, then this
%       matrix has dimensions e by n.  Each row of E has only two non-zero
%       entries - a "1" and a "-1."
%     v: A matrix of normalized direction vectors corresponding to the
%       edges measured by the linear operator E.  For a recovery with n
%       points in d dimensions, and e directional measurements, v should be 
%       of size e by d.  Given a matrix x containing one cloud point per
%       row, the matrix v can be generated by computing v=E*x.
%    
%   The method solves the problem
%     min_x |Perp(E*x)| subject to mean(x)=0, sum{(x_i-x_j)^T*v_ij}=1.
%   This is done using an ADMM formulation with Lagrangian
%       min_{x,y} |Perp(y)| + t/2||E*x-y+l||^2, st mean(x)=0 and sum (x_i-x_j)^T*v_ij =1
%   where y is an auxilliary variable containing edge directions in the
%   recovered graph, and l is an array of Lagrange Multipliers.

function [x, resids] = solve_shapefit(E,v, verbose)

if ~exist('verbose','var')
    verbose = false;
end

%% record problem parameters
maxIters = 1000;
n = size(E,2);  % number of points to be recovered
d = size(v,2);  % dimension of each point
e = size(E,1);  % number of measurements we are given
%% allocate memory
y = zeros(e,d); % stores recovered edges
x = zeros(n,d); % stores recovered points
l = zeros(e,d); % Lagrange multipliers - enforce that edges correspond to points
t = 1000/n;    % choose stepsize.  Solver is actually not very sensitive to this
maxResid = 0;

%% ensure that direction data is normalized
norms = sqrt(sum(v.*v,2));
v = v./(norms*ones(1,d));  % each vector is now of unit norm

%% Pre-compute linear summation constraint, i.e. sum (x_i-x_j)^T*v_ij =1
%  This constraint can be written C'*x=1 for some C
C = E'*v;

%% Pre-compute the matrix inverse for the least-squares step
%      minimize ||Mx-v||^2 subject to mean(x)=0, sum (x_i-x_j)^T*v_ij =1
%  The system to be factored is
% [ S  C' ] = rhs
% [ C'  0 ]
%  The solution is found using a block inverse formula
S = [E;ones(1,n)];  % augment least-squares term to penalize mean(x)
S = full(S'*S);     % form Hessian Matrix
Sinv = pinv(S);      % This matrix is well conditioned, so we just use the inverse to save time
SinvC = Sinv*C;     % precompute this component of the block inversion formula
schur_comp = -sum(sum(C.*(SinvC)));  % The schur complement of the system is 1x1 because there's only 1 explicit constraint
store = SinvC/schur_comp;
solve_system = @(v)   Sinv*(E'*v)+ store*(sum(sum(SinvC.*(E'*v)))-1);

%% Begin ADMM iteration
resids=zeros(maxIters,1);  %  residuals are stored for plotting
primals=zeros(maxIters,1);  %  residuals are stored for plotting
duals=zeros(maxIters,1);  %  residuals are stored for plotting
error = 0;
error0 = 0;
for i=1:maxIters
    x0 = x; % record stale iterate
    errorm1=error0;
    error0 = error;
    %% Update x
    x = solve_system(y-l);
    %% Update v
    % Compute the right hand side for least-squares problem
    y = E*x+l;
    % Decompose y into the space parallel to v, and perpendicular to y
    prods = sum(y.*v,2);        % compute inner products with normalized directions
    Py = v.*(prods*ones(1,d));  % Projection of y onto v
    perp = y - Py;  %  Projection onto V_perp
    % Shrink the perp component
    norms = sqrt(sum(perp.*perp,2));
    scale = max(norms-1/t,0)./(norms+(norms<1e-13));
    % Reconstitute the solution by adding the two components together
    y = Py+perp.*(scale*ones(1,d));  % L2 shrink

    %% Update Lagrange multipliers
    error = E*x-y;
    l = l+1.9*error;  

    %%  Compute residuals to measure convergence
    primal_resid = norm(error,'fro')/norm(y,'fro');
    dual_resid = t*norm(x-x0,'fro')/norm(x,'fro');
    resid = primal_resid + dual_resid;
    resids(i) = resid;
    primals(i) = primal_resid;
    duals(i) = dual_resid;
    maxResid = max(maxResid,resid);
    relResid = resid/maxResid;
    % compute objective energy
    energy = norm(perp,'fro')+t/2*norm(error+l,'fro')^2; % the Lagrangian objective

    %% The secret sauce!
    %% "Kicking" to accelerate convergence:  increase stepsize parameter if the method stalls
    if  i>5 && t<1e6 && norm(error+errorm1-2*error0)/norm(error)<1e-3  %  use second derivative to see if error is changing linearly
        l = l/10;
        t = t*10;
    end
    
    % print convegence data every 10 iterations
    if verbose && mod(i,50)==0
        objective = shapefit_energy(E,v,x);
        fprintf('%d: residual=%f  objective=%f  t=%2.1d\n', i, relResid, objective, t);
    end
    

    %% Check stopping conditions
    if relResid < 1e-5
        resids = resids(1:i);
        break
    end

end
